kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
    - docker build -t drone-tests .

#- name: run
#  commands:
#    - cd /var/docker/drone-tests
#    - docker-compose stop drone-tests
#    - docker-compose up -d drone-test